<?php require("../../includes/header.php"); ?><h1>Fault Tolerance</h1><div class="content">

<p>Chef has a set of very large set of very important data he doesn't want to lose. Chef has a number of servers on which he stores the data. To store the data, Chef begins by splitting his data into chunks. Then he assigns a set of chunks to each server. For the sake of redundancy, the same chunk may be assigned to multiple servers. If multiple chunks are assigned to the same server, there will not be enough space to store all of the chunks individually, so instead the chunks are combined together. When multiple chunks are combined together it is no longer possible to retrieve the data from the original chunks. However, by combining data from multiple servers it may be possible to retrieve the original data.</p>
<p>Denote <b>A ⊕ B</b> as the result of combining chunks <b>A</b> and <b>B</b>. The following properties hold:</p>
<ul>
<li><b>A ⊕ B = B ⊕ A</b></li>
<li><b>(A ⊕ B) ⊕ C = A ⊕ (B ⊕ C)</b></li>
<li><b>(A ⊕ A) ⊕ B = B</b></li>
</ul>
<p>Note that the first two properties imply that when combining more than two chunks, the order in which they are combined does not matter.</p>
<p>Let's consider an example (this example will coincide with the sample input below). There are <b>4</b> chunks of data, and <b>6</b> servers. Denote <b>C<sub>i</sub> (0 ≤ i &lt; 4)</b> as the original chunks of data, and <b>S<sub>j</sub> (0 ≤ j &lt; 6)</b> as the data stored on the servers. Chef combines chunks as follows:</p>
<ul>
<li><b>S<sub>0</sub> = C<sub>2</sub></b></li>
<li><b>S<sub>1</sub> = C<sub>0</sub> ⊕ C<sub>3</sub></b></li>
<li><b>S<sub>2</sub> = C<sub>0</sub> ⊕ C<sub>2</sub></b></li>
<li><b>S<sub>3</sub> = C<sub>1</sub> ⊕ C<sub>3</sub></b></li>
<li><b>S<sub>4</sub> = C<sub>0</sub> ⊕ C<sub>1</sub> ⊕ C<sub>2</sub></b></li>
<li><b>S<sub>5</sub> = C<sub>0</sub> ⊕ C<sub>1</sub></b></li>
</ul>
<p>One way Chef may recover the original data is as follows:</p>
<ul>
<li><b>C<sub>0</sub> = S<sub>0</sub> ⊕ S<sub>2</sub></b></li>
<li><b>C<sub>1</sub> = S<sub>2</sub> ⊕ S<sub>4</sub></b></li>
<li><b>C<sub>2</sub> = S<sub>0</sub></b></li>
<li><b>C<sub>3</sub> = S<sub>2</sub> ⊕ S<sub>3</sub> ⊕ S<sub>4</sub></b></li>
</ul>
<p>Chef is now interested in how safe his data is. If the data from some servers is lost it may be impossible to recover the original data. Chef would like you to find a set of servers such that simultaneous failure would make some part of his data irrecoverable. Chef prefers that you find a small set of servers, but does not require minimality. Smaller sets will score more points.</p>
<h3>Input</h3>
<p>Each test file contains only one test case.</p>
<p>The first line of input contains <b>2</b> space-separated integers <b>N</b> and <b>S</b>, denoting the number of chunks and number of servers, respectively. Then <b>S</b> lines follow, each with a description of the chunks stored on one server. A server description consists of an integer <b>C</b> denoting the number of chunks assigned to this server, followed by <b>C</b> integers denoting the ids of the chunks assigned to this server. Chunks are numbered from <b>0</b> to <b>N−1</b> and servers numbered <b>0</b> to <b>S−1</b>.</p>
<h3>Output</h3>
<p>First output an integer <b>K</b>, the number of failing servers in your solution. Then output the distinct ids of the failing servers.</p>
<h3>Constraints</h3>
<ul>
<li><b>50 ≤ N ≤ 200</b></li>
<li><b>2*N ≤ S ≤ 1000</b></li>
<li><b>1 ≤ C ≤ N</b></li>
<li>Each server stores distinct chunks.</li>
<li>Chef can recover the original data if no servers are lost.</li>
<li>All official test files are generated by the method written in Test Case Generation.</li>
</ul>
<p>Note that the following Sample Input does not satisfy the constraints.</p>
<h3>Scoring</h3>
<p>Your score for each test file is <b>10*K/(S−N+1)</b>. The total score is the average of scores over all test files. The goal is to minimize your score.</p>
<h3>Example</h3>
<pre><b>Input:</b>
4 6
1 2
2 0 3
2 0 2
2 1 3
3 0 1 2
2 0 1

<b>Output:</b>
1
2
</pre><h3>Explanation</h3>
<p>This sample output would score <b>10*1/(6−4+1) = 3.333...</b>. If server <b>2</b> is lost, there is no way to recover data chunks <b>0</b>, <b>1</b>, or <b>3</b>.</p>
<h3>Test Case Generation</h3>
<p>The judge has <b>40</b> official test files.</p>
<p>An integer <b>N</b> is chosen randomly and uniformly between <b>50</b> and <b>200</b>, inclusive. Then an integer <b>S</b> is chosen randomly and uniformly between <b>2*N</b> and <b>1000</b>, inclusive. A real number <b>P</b> is chosen randomly and uniformly between <b>0.3</b> and <b>0.8</b>, inclusive, and each chunk is assigned to each server with probability <b>P</b>. The order of the chunks assigned to each server is shuffled.</p>
<p>If a generated test does not satisfy the constraints, then the test is discarded.</p>
    </div><table cellspacing="0" cellpadding="0" align="left">
        <tr>
            <td width="14%">Author:</td>
            <td><a href="/users/pieguy">pieguy</a></td>
		</tr>
						<tr>
					<td width="14%">Tester:</td>
					<td><a href="/users/laycurse">laycurse</a></td>
				</tr>
								
		                
        		<tr>
            <td width="14%">Date Added:</td>
            <td>7-02-2013</td>
        </tr>
        <tr>
            <td width="14%">Time Limit:</td>
            <td>1 sec</td>
        </tr>
        <tr>
            <td width="14%">Source Limit:</td>
            <td>50000 Bytes</td>
        </tr>
        <tr>
            <td width="14%">Languages:</td>
            <td>ADA, ASM, BASH, BF, C, C99 strict, CAML, CLOJ, CLPS, CPP 4.3.2, CPP 4.8.1, CPP11, CS2, D, ERL, FORT, FS, GO, HASK, ICK, ICON, JAR, JAVA, JS, LISP clisp, LISP sbcl, LUA, NEM, NICE, NODEJS, PAS fpc, PAS gpc, PERL, PERL6, PHP, PIKE, PRLG, PYTH, PYTH 3.1.2, RUBY, SCALA, SCM guile, SCM qobi, ST, TCL, TEXT, WSPC</td>
        </tr>
    </table> <?php require("../../includes/footer.php"); ?>