<?php require("../../includes/header.php"); ?><h1>Generalized Arithmetic Progression Free Sequence</h1><div class="content">

<p>
For given two positive integers <b>a</b> and <b>b</b> let's construct the sequence <b>x[1], x[2], ...</b> by the following rules. For <b>k=1</b> we put <b>x[1]=1</b>. Now let <b>k &gt;= 2</b>. Then <b>x[k]</b> is the least positive integer such that the following two conditions hold</p>
<ul>
<li><b>x[k] &gt; x[k - 1]</b>;
</li>
<li> for all <b>i, j &lt; k</b> we have <b>x[k]</b> is not equal to <b>a * x[i] - b * x[j]</b>.
</li>
</ul>
<p>
You need to find the first <b>n</b> terms of this sequence.</p>
<p><b>Remark.</b> Let <b>a=2</b> and <b>b=1</b>. Then we see that sequence <b>x[1], x[2], ...</b> does not contain any arithmetic progression of length three as its subsequence. This justifies the problem title.
</p>
<h3>Input</h3>
<p>
The first line contains a single integer <b>T</b>, the number of test cases. <b>T</b> test cases follow. The only line of each test case contains three integers <b>a, b</b> and <b>n</b>.
</p>
<h3>Output</h3>
<p> For each test case, output a single line containing the numbers <b>x[1], x[2], ..., x[n]</b> generated by the rules given in the problem statement and numbers <b>a, b</b>. Separate any two consecutive numbers in a line by a single space.</p>
<h3>Constraints</h3>

<p><b><br />
1 &lt;= T &lt;= 50<br />
<br />
1 &lt;= a, b &lt;= 50<br />
<br />
1 &lt;= n &lt;= 1000<br />
</b></p>
<h3>Example</h3>
<pre>
<b>Input:</b>
3
2 1 10
1 1 5
4 2 4

<b>Output:</b>
1 2 4 5 10 11 13 14 28 29
1 2 3 4 5
1 3 4 5
</pre>    </div><table cellspacing="0" cellpadding="0" align="left">
        <tr>
            <td width="14%">Author:</td>
            <td><a href="/users/anton_lunyov">anton_lunyov</a></td>
		</tr>
						<tr>
					<td width="14%">Tester:</td>
					<td><a href="/users/pieguy">pieguy</a></td>
				</tr>
								
		                
        		<tr>
            <td width="14%">Date Added:</td>
            <td>5-10-2011</td>
        </tr>
        <tr>
            <td width="14%">Time Limit:</td>
            <td>5 sec</td>
        </tr>
        <tr>
            <td width="14%">Source Limit:</td>
            <td>50000 Bytes</td>
        </tr>
        <tr>
            <td width="14%">Languages:</td>
            <td>ADA, ASM, BASH, BF, C, C99 strict, CAML, CLOJ, CLPS, CPP 4.3.2, CPP 4.8.1, CPP11, CS2, D, ERL, FORT, FS, GO, HASK, ICK, ICON, JAR, JAVA, JS, LISP clisp, LISP sbcl, LUA, NEM, NICE, NODEJS, PAS fpc, PAS gpc, PERL, PERL6, PHP, PIKE, PRLG, PYTH, PYTH 3.1.2, RUBY, SCALA, SCM guile, SCM qobi, ST, TCL, TEXT, WSPC</td>
        </tr>
    </table> <?php require("../../includes/footer.php"); ?>