<?php require("../../includes/header.php"); ?><h1>Efficient Painting</h1><div class="content">

<p>Chef recently took up painting. He likes painting pictures, but is always thinking of ways to make painting more efficient. Chef begins with a square canvas, initially painted completely white. He paints one rectangle at a time, where every edge must have integer length, and 2 edges of the rectangle must be parallel to the horizontal axis. When Chef paints a rectangle, he paints it in one of the following ways:</p>
<ul>
<li>White - paint the entire rectangle white</li>
<li>Black - paint the entire rectangle black</li>
<li>Flip - All white paint inside the rectangle becomes black, and all black paint becomes white</li>
</ul>

<p>Chef wants your help in order to paint as few rectangles as possible. You will be given the final picture that Chef intends to paint.  You must come up with a plan to paint the picture. Chef knows this is a difficult problem, so he isn't requiring optimal solutions, but the fewer rectangles you use the more points you will score.</p>
<h3>Input</h3>
<p>Input will begin with an integer <b>N</b>, the size of the painting. <b>N</b> lines follow with <b>N</b> characters each, describing the picture chef wishes to paint. The top-left corner is <b>(0, 0)</b>, the top-right corner is <b>(0, N−1)</b>, the bottom-left corner is <b>(N−1, 0)</b>, and the bottom-right corner is <b>(N−1, N-1)</b>. A 'W' character indicates the corresponding cell of the painting is white, and a 'B' character indicates the cell is black.</p>
<h3>Output</h3>
<p>First output an integer <b>L</b>, the number of rectangles in your solution. This number must not exceed <b>N</b><sup>2</sup>. Then output <b>L</b> lines. Each line should consist of 2 pairs of integers followed by a 'W', 'B', or 'F' character. The first pair of integers is the <b>(row, column)</b> coordinates of the upper-left corner of the rectangle, and the second pair is the <b>(row, column)</b> coordinates of the bottom-right corner. The final character indicates the operation to perform on the rectangle, 'W' for white, 'B' for black, and 'F' for flip.</p>
<h3>Constraints</h3>
<p><b>10 ≤ N ≤ 50</b> (excepting Sample Input)<br />All official inputs are generated by the method described in Test Generation.</p>
<h3>Scoring</h3>
<p>Your score for each test file is <b>10*L/N<sup>2</sup></b>. Your overall score is the average of your scores on the individual test files. The goal is to minimize your score.</p>
<h3>Sample Input</h3>
<pre><code>5
BWBBB
BBBWW
BBWWB
BBWWB
WBBBW
</code></pre><h3>Sample Output</h3>
<pre>5
0 0 3 4 B
2 2 4 3 F
4 1 4 1 B
0 1 0 1 W
1 3 1 4 W
</pre><h3>Explanation</h3>
<p>The painting of the grid proceeds as follows:</p>
<pre><code>WWWWW
WWWWW
WWWWW
WWWWW
WWWWW

<b>BBBBB</b>
<b>BBBBB</b>
<b>BBBBB</b>
<b>BBBBB</b>
WWWWW

BBBBB
BBBBB
BB<b>WW</b>B
BB<b>WW</b>B
WW<b>BB</b>W

BBBBB
BBBBB
BBWWB
BBWWB
W<b>B</b>BBW

B<b>W</b>BBB
BBBBB
BBWWB
BBWWB
WBBBW

BWBBB
BBB<b>WW</b>
BBWWB
BBWWB
WBBBW
</code></pre><p>This sample output would score <b>10*5/5<sup>2</sup> = 2</b>.</p>
<h3>Test Generation</h3>
<p>We have <b>50</b> official test cases, each of them is created as follows:</p>
<p>An integer <b>N</b> is chosen from <b>[10, 50]</b> uniformly at random. An real value <b>p</b> is chosen from <b>[0.4, 0.6]</b> uniformly at random. Then each cell is independently chosen as 'B' with probability <b>p</b>, 'W' with probability <b>1 − p</b>.</p>
    </div><table cellspacing="0" cellpadding="0" align="left">
        <tr>
            <td width="14%">Author:</td>
            <td><a href="/users/pieguy">pieguy</a></td>
		</tr>
						<tr>
					<td width="14%">Tester:</td>
					<td><a href="/users/laycurse">laycurse</a></td>
				</tr>
								
		                
        		<tr>
            <td width="14%">Date Added:</td>
            <td>7-01-2013</td>
        </tr>
        <tr>
            <td width="14%">Time Limit:</td>
            <td>1 sec</td>
        </tr>
        <tr>
            <td width="14%">Source Limit:</td>
            <td>50000 Bytes</td>
        </tr>
        <tr>
            <td width="14%">Languages:</td>
            <td>ADA, ASM, BASH, BF, C, C99 strict, CAML, CLOJ, CLPS, CPP 4.3.2, CPP 4.8.1, CPP11, CS2, D, ERL, FORT, FS, GO, HASK, ICK, ICON, JAR, JAVA, JS, LISP clisp, LISP sbcl, LUA, NEM, NICE, NODEJS, PAS fpc, PAS gpc, PERL, PERL6, PHP, PIKE, PRLG, PYTH, PYTH 3.1.2, RUBY, SCALA, SCM guile, SCM qobi, ST, TCL, TEXT, WSPC</td>
        </tr>
    </table> <?php require("../../includes/footer.php"); ?>