<?php require("../../includes/header.php"); ?><h1>Lucky Name</h1><div class="content">

<p>Thapar University has changed its placement rules this year. Companies coming for campus placement have decided to give salary to the student who are selected in the interviews on basis of their name. They have developed a software which takes input as the string (student name) and displays the output as a number. Salary given by the company is the number which is generated by the software. Your task is to develop the software for the campus placement. Think about the logic how this software could have been made by judjing the input and output.</p>
<h3>Input</h3>
<p>The first line contains integer t, the number of test cases followed by t strings (each of length &lt; 9 )</p>
<h3>Output</h3>
<p>Ouput consists of a number for every string.</p>
<h3>Example</h3>
<pre>
<b>Input:</b>
6
ravi
Jatin
Aakash
Aranya
chunky
raj

<b>Output:</b>
109
101
101
101
113
107
</pre>    </div><table cellspacing="0" cellpadding="0" align="left">
        <tr>
            <td width="14%">Author:</td>
            <td><a href="/users/Chunky">Chunky</a></td>
		</tr>
				                
        		<tr>
            <td width="14%">Date Added:</td>
            <td>14-08-2010</td>
        </tr>
        <tr>
            <td width="14%">Time Limit:</td>
            <td>4 sec</td>
        </tr>
        <tr>
            <td width="14%">Source Limit:</td>
            <td>50000 Bytes</td>
        </tr>
        <tr>
            <td width="14%">Languages:</td>
            <td>C, CPP 4.3.2, CPP 4.8.1, CPP11, GO, JAVA, NODEJS</td>
        </tr>
    </table> <?php require("../../includes/footer.php"); ?>