<?php require("../../includes/header.php"); ?><h1>Killing Gs</h1><div class="content">

<p>
There are the big enemies for all chefs, that is, <i>G</i>s (the plural form of <i>G</i>).<br />
Chef Ciel find <strong>N</strong> Gs in her restaurant.<br />
Ciel is very scared, and she is going to kill the Gs by using insecticides.<br />
Here <strong>M</strong> insecticides are available,<br />
and the price of the <strong>j</strong>-th insecticide is <strong>C<sub>j</sub></strong>, and she can use the <strong>j</strong>-th insecticide for all <strong>N</strong> Gs if she buys it.<br />
Unfortunately Gs may have resistance to insecticides, so Gs may be still alive after using some insecticides.<br />
But we know that if Ciel use the <strong>j</strong>-th insecticide, the <strong>i</strong>-th G will be dead with the probability <strong>P</strong><sub><strong>i</strong>,<strong>j</strong></sub>%, and these are statistically independent.
</p>
<p>
Chef Ciel would like to buy some insecticides, and then, Ciel may use the insecticides one by one.<br />
Ciel hopes that the <strong>i</strong>-th G will be dead with a probability at least 90%, for all <strong>i</strong>, after using all insecticides which she buys.
</p>
<p>
Your work is selecting a cheaper (cheapest is not necessary) set of distinct insecticides which she buys.<br />
Don't forget that the set must kill the <strong>i</strong>-th G with a probability at least 90% for all <strong>i</strong>.
</p>
<h3>Input</h3>
<p>
The first line contains an integer <strong>T</strong>, the number of test cases.<br />
Then <strong>T</strong> test cases follow.<br />
The first line for each test case has 2 integers <strong>N</strong> and <strong>M</strong>.<br />
The next line has <strong>M</strong> integers <strong>C</strong><sub>1</sub>, <strong>C</strong><sub>2</sub>, ..., <strong>C<sub>M</sub></strong>.<br />
Then next <strong>N</strong> lines have <strong>M</strong> integers <strong>P</strong><sub><strong>i</strong>,<strong>j</strong></sub>, that is the <strong>j</strong>-th integer of the <strong>i</strong>-th line.
</p>
<h3>Output</h3>
<p>
For each test case, you should print two lines.<br />
The first line should have an integer <strong>K</strong>, the number of insecticides which Ciel buys.<br />
The second line should have <strong>K</strong> integers, the numbers of insecticides which Ciel buys, in ascending order.
</p>
<h3>Constraints</h3>
<p>
<strong>T</strong> = 50 (except for Sample Input)<br />
50 &le; <strong>N</strong> &le; 200 (except for Sample Input)<br />
50 &le; <strong>M</strong> &le; 200 (except for Sample Input)<br />
1 &le; <strong>C<sub>j</sub></strong> &le; 1000000 (10<sup>6</sup>)<br />
0 &le; <strong>P</strong><sub><strong>i</strong>,<strong>j</strong></sub> &le; 90<br />
The probability of killing the <strong>i</strong>-th G is at least 90% for all <strong>i</strong>, if Ciel buys all insecticides.
</p>
<h3>Scoring</h3>
<p>
For each test case, the score is defined as (<strong>basic</strong> - <strong>your</strong>) / <strong>basic</strong>, where <strong>your</strong> is the cost of your set and <strong>basic</strong> is the cost of the set given by <a href="http://www.codechef.com/download/CKROACH_simplesolution.c">CKROACH_simplesolution.c</a>.<br />
If the score is negative, it is treated as 0.<br />
Your objective is to maximize the total score.
</p>
<h3>Test Case Generation</h3>
<p>
There is only one input file for this problem. Each test case generated by the below method.
</p>
<p>
<strong>N</strong>, <strong>M</strong> and <strong>P</strong><sub><strong>i</strong>,<strong>j</strong></sub> are chosen uniformly at random such that they satisfy constraints.<br />
After that, each <strong>P</strong><sub><strong>i</strong>,<strong>j</strong></sub> becomes 0 with the probability 0.75.<br />
Then an integer <strong>x</strong> is chosen from the set {1, 2, 5, 10, 100} uniformly at random.<br />
For each <strong>j</strong> (1 &le; <strong>j</strong> &le; <strong>M</strong>),<br />
a real number <strong>y</strong><sub><strong>j</strong></sub> is chosen from [0, 1) uniformly at random,<br />
and <strong>C</strong><sub><strong>j</strong></sub> is set at (<strong>x</strong> + <strong>y</strong><sub><strong>j</strong></sub>) * (<strong>P</strong><sub>1,<strong>j</strong></sub> + <strong>P</strong><sub>2,<strong>j</strong></sub> + ... + <strong>P</strong><sub><strong>N</strong>,<strong>j</strong></sub>) rounded to the nearest integer.<br />
If <strong>C<sub>j</sub></strong> is less than 1, then <strong>C<sub>j</sub></strong> becomes 1.<br />
If <strong>C<sub>j</sub></strong> is more than 1000000, then <strong>C<sub>j</sub></strong> becomes 1000000.
</p>
<p>
Finally, if the generated case does not satisfy the constraint "The probability of killing the <strong>i</strong>-th G is at least 90% for all <strong>i</strong>, if Ciel buys all insecticides", this case is destroyed and do the above process once again.
</p>
<p>
A test case generator is available <a href="http://www.codechef.com/download/CKROACH_generator.c">here</a>.
</p>
<h3>Sample Input</h3>
<pre>2
2 3
100 100 190
90 0 90
0 90 90
1 5
10 20 40 60 85
10 20 40 60 85
</pre><h3>Sample Output</h3>
<pre>1
3
2
3 5</pre><h3>Output details</h3>
<p>
In the first case, the third insecticide will kill the <strong>i</strong>-th G with probability 90% for all <strong>i</strong>.
</p>
<p>
In the second case, after using the third and fifth insecticides,<br />
G is still alive with the probability (1 - 40/100) * (1 - 85/100) = 0.6 * 0.15 = 0.09.<br />
Therefore the set of the third and fifth insecticides will kill the G with the probability 91%.
</p>
<p>
The output for Sample Input of <a href="http://www.codechef.com/download/CKROACH_simplesolution.c">CKROACH_simplesolution.c</a> is the following. (which is far from the optimal)
</p>
<pre>2
1 2
5
1 2 3 4 5</pre>    </div><table cellspacing="0" cellpadding="0" align="left">
        <tr>
            <td width="14%">Author:</td>
            <td><a href="/users/laycurse">laycurse</a></td>
		</tr>
						<tr>
					<td width="14%">Tester:</td>
					<td><a href="/users/subra">subra</a></td>
				</tr>
								
		                
        		<tr>
            <td width="14%">Date Added:</td>
            <td>21-09-2011</td>
        </tr>
        <tr>
            <td width="14%">Time Limit:</td>
            <td>30 sec</td>
        </tr>
        <tr>
            <td width="14%">Source Limit:</td>
            <td>50000 Bytes</td>
        </tr>
        <tr>
            <td width="14%">Languages:</td>
            <td>ADA, ASM, BASH, BF, C, C99 strict, CAML, CLOJ, CLPS, CPP 4.3.2, CPP 4.8.1, CPP11, CS2, D, ERL, FORT, FS, GO, HASK, ICK, ICON, JAR, JAVA, JS, LISP clisp, LISP sbcl, LUA, NEM, NICE, NODEJS, PAS fpc, PAS gpc, PERL, PERL6, PHP, PIKE, PRLG, PYTH, PYTH 3.1.2, RUBY, SCALA, SCM guile, SCM qobi, ST, TCL, TEXT, WSPC</td>
        </tr>
    </table> <?php require("../../includes/footer.php"); ?>